### PR TITLE
Fix: Issue of synchronizing namespaced local memory caches

### LINKED ISSUE #32: With a bus, `clear`ing a namespace will clear the entire cache
Unless I'm mistaken, when publishing the `Clear` message to the bus, we are not providing it with the namespace name (https://github.com/Julien-R44/bentocache/blob/9d66e2f14c41936493d7af6b1d23a14c44bdb192/packages/bentocache/src/cache/cache.ts#L255) and as such, all subscribed caches (including the `root`) will clear the cache (https://github.com/Julien-R44/bentocache/blob/9d66e2f14c41936493d7af6b1d23a14c44bdb192/packages/bentocache/src/bus/bus.ts#L65); right?

### PR DESCRIPTION
**Pull request by gkachru**
Changes to namespaced local memory caches do not get pushed correctly.

When the CacheStack is namespaced, it creates a namespaced version of the l1 drivers, however does not create a new bus with the modified l1 driver. This change fixes that.

Added some test cases as well. Should fix #32

### CODE REVIEW

**Comment by Julien-R44** [comment]
Looks perfect! 
Thanks a lot for taking the time to fix this issue

**Comment by wodCZ** [comment]
@Julien-R44  could we get a release pretty please? 🙏 Wanted to try this fix, but I'm running into [other issue](https://github.com/yarnpkg/berry/issues/5715) when trying to install from main.

**Comment by Julien-R44** [comment]
@wodCZ Yup sorry! Release with 1.0.0-beta.10

**Comment by wodCZ** [comment]
Hmm. I might have misunderstood the goal of this PR, but I'm still having issues with namespace synchronization across multiple processes.

I've created a minimal reproduction: https://github.com/wodCZ/bentocache-bus-repro

**Comment by Julien-R44** [comment]
Thanks for the repro dude !

There is indeed an issue going on. Let me check that

**Comment by gkachru** [comment]
Different issue with BinaryEncoding not handling the Clear message correctly. #38 should fix it.

**Comment by Julien-R44** [comment]
Released with beta.11

File: packages/bentocache/src/cache/stack/cache_stack.ts [hunk 1]
```diff
@@ -46,22 +48,23 @@ export class CacheStack {
...
-        l2Driver: this.l2?.namespace(namespace),
-      },
-      this.bus,
-    )
+    return new CacheStack(this.name, this.options, {
+      l1Driver: this.l1?.namespace(namespace),
+      l2Driver: this.l2?.namespace(namespace),
+      busDriver: this.#busDriver,
+      busOptions: this.#busOptions,
+    })
```
Comment (wodCZ) [inline packages/bentocache/src/cache/stack/cache_stack.ts:67]: @gkachru  I believe, there should be 4th argument passed with `this.bus`, otherwise a new bus is created every time any namespace is accessed.

This can be seen in https://github.com/wodCZ/bentocache-bus-repro, if you run the `main.js`, you see the following error after 10 logs:
```
(node:70661) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 reconnecting listeners added to [Commander]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at _addListener (node:events:593:17)
    at EventEmitter.addListener (node:events:611:10)
    at RedisTransport.onReconnect (file:///Users/wod/sites/bentotest/node_modules/@boringnode/bus/build/src/transports/redis.js:68:26)
    at new Bus (file:///Users/wod/sites/bentotest/node_modules/@boringnode/bus/build/src/bus.js:28:38)
    at new Bus (file:///Users/wod/sites/bentotest/node_modules/bentocache/build/index.js:588:17)
    at #createBus (file:///Users/wod/sites/bentotest/node_modules/bentocache/build/index.js:1098:20)
    at new _CacheStack (file:///Users/wod/sites/bentotest/node_modules/bentocache/build/index.js:1076:31)
    at _CacheStack.namespace (file:///Users/wod/sites/bentotest/node_modules/bentocache/build/index.js:1102:12)
```

Thanks for the amazing work otherwise 🙏

Comment (wodCZ) [reply packages/bentocache/src/cache/stack/cache_stack.ts:67]: PS: just checked adding the 4th arg locally and the memory leak warning is gone, while both namespace sync issues remain fixed.

Comment (gkachru) [reply packages/bentocache/src/cache/stack/cache_stack.ts:67]: The bus does indeed need to be created every time, as you need to pass in the new namespace localcache instance. It is however generally a memory intensive way as both CacheStack and bus get created.

The event emitter warning can be eliminated by setting up something like `const bcProducts = bento.namespace('products')` and then using `bcProducts.set` etc from then on. However, still you would have as many CacheStack and bus instances as there are namespaces, plus one for the original bento instance.

The reason why `.clear()` still works as you pass in the original bus, is because all buses are listening to the same queue name! So the `clear` message is received by every instance of the bus, both the namespaced and non-namespaced one, which will clear all items everywhere!

Have noticed this, and I am working on this issue as well.

Comment (gkachru) [reply packages/bentocache/src/cache/stack/cache_stack.ts:67]: Added PR #39 to address the excessive messages by namespacing the bus channel.
